name: ci

on:
  push:
    paths:
       - src/** 
    branches:
        - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: adinagesh/python-app:${{ env.COMMIT_ID }}
    outputs:
        commit_id: ${{env.COMMIT_ID}}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app/values.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

          
      - name: install argocd
        shell: bash
        run: |
         ARGOCD_VERSION=$(curl --silent "https://api.github.com/repos/argoproj/argo-cd/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
         curl -sSL -o /tmp/argocd-${ARGOCD_VERSION} https://github.com/argoproj/argo-cd/releases/download/${ARGOCD_VERSION}/argocd-linux-amd64
         chmod +x /tmp/argocd-${ARGOCD_VERSION}
         sudo mv /tmp/argocd-${ARGOCD_VERSION} /usr/local/bin/argocd 
         argocd version --client
      - name: argocd app sync 
        shell: bash
        run: |
          argocd version --client
          argocd login argocd-server.argocd \
           --insecure \
           --grpc-web \
           --username admin \
           --password ${{secrets.ARGOCD_PASSWORD}}
          argocd app sync python-app

